
    export const exercises = [
        "Push-Ups",
        "Sit-Ups",
        "Barbell Back Squats",
        "Lunges",
        "Planks",
        "Jumping Jacks",
        "Burpees",
        "High Knees",
        "Mountain Climbers",
        "Tuck Jumps",
        "Pull-Ups",
        "Chin-Ups",
        "Bicep Curls",
        "Tricep Dips",
        "Incline Dumbell Bench Press",
        "Flat Dumbell Bench Press",
        "Ankle Plyos",
        "Nordic Hamstring Curls",
        "Side ro Side jumps",
        "Deadlifts",
        "Bench Press",
        "Leg Press",
        "Shoulder Press",
        "Lat Pulldowns",
        "Dumbbell Rows",
        "Dumbbell Flyes",
        "Skull Crushers",
        "Leg Curls",
        "Leg Extensions",
        "Calf Raises",
        "Hammer Curls",
        "Front Raises",
        "Front Squats",
        "Lateral Raises",
        "Dumbbell Pullovers",
        "Face Pulls",
        "Pec Deck Flyes",
        "Russian Twists",
        "Leg Raises",
        "Bicycle Crunches",
        "Flutter Kicks",
        "Hanging Leg Raises",
        "Box Jumps",
        "Step-Ups",
        "Treadmill Running",
        "Elliptical",
        "Rowing Machine",
        "Stationary Bike",
        "Jump Rope",
        "Battle Ropes",
        "Kettlebell Swings",
        "Kettlebell Snatches",
        "Goblet Squats",
        "Kettlebell Deadlifts",
        "Turkish Get-Ups",
        "Wall Sits",
        "Bulgarian Split Squats",
        "Pistol Squats",
        "Dumbbell Step-Ups",
        "Barbell Rows",
        "T-Bar Rows",
        "Barbell Shrugs",
        "Dumbbell Shrugs",
        "Hip Thrusts",
        "Glute Bridges",
        "Bear Crawls",
        "Arm Circles",
        "Dumbbell Side Bends",
        "Woodchoppers",
        "Barbell Rollouts",
        "Single Leg Deadlifts",
        "Concentration Curls",
        "Zottman Curls",
        "Spider Curls",
        "Close-Grip Bench Press",
        "Diamond Push-Ups",
        "Tricep Kickbacks",
        "Overhead Tricep Extensions",
        "Single Arm Dumbbell Press",
        "Lying Leg Raises",
        "Windshield Wipers",
        "Barbell Twists",
        "Farmer's Walk",
        "Single Arm Dumbbell Rows",
        "Single Leg Hops",
        "Bosu Ball Squats",
        "Medicine Ball Slams",
        "Medicine Ball Chest Pass",
        "Medicine Ball Rotational Throws",
        "Ladder Drills",
        "Cone Drills",
        "TRX Rows",
        "TRX Pistol Squats",
        "TRX Mountain Climbers",
        "Barbell Front Squats",
        "Barbell Hack Squats",
        "Sumo Deadlifts",
        "Romanian Deadlifts"
    ];
    
